package sudoku;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bobby Squires
 */
public class MainMenu extends javax.swing.JFrame {

    // Declaring variables
    private int elapsedTime = 0, seconds = 0, minutes = 0, playerTime = 0;
    private String timerSeconds = String.format("%02d", seconds);
    private String timerMinutes = String.format("%02d", minutes);
    private SudokuBoard gameboard;
    private ArrayList<javax.swing.JTextField> positions;
    boolean timerStarted = false;

    /*
    * Source for timer:
    * https://www.youtube.com/watch?v=0cATENiMsBE
     */
    // ActionListener event to create game timer
    Timer gameTimer = new Timer(1000, new ActionListener() {

        public void actionPerformed(ActionEvent e) {

            elapsedTime = elapsedTime + 1000;
            minutes = (elapsedTime / 60000) % 60;
            seconds = (elapsedTime / 1000) % 60;
            timerSeconds = String.format("%02d", seconds);
            timerMinutes = String.format("%02d", minutes);
            timerLabel.setText(timerMinutes + ":" + timerSeconds);
        }
    });

    // Default constructor
    public MainMenu() throws FileNotFoundException, IOException {
        initComponents();
        positions = new ArrayList();
        gameboard = new SudokuBoard();
        SelectDifficulty.loadBoards();
        LeaderBoardScore.loadScores();
        loadList();
        populateLeaderboard();
        selectDifficultyPanel.setVisible(true);
        showLeaderboardPanel.setVisible(true);
        gameboardPanel.setVisible(true);
        checkSolutionButton.setVisible(false);
        showSolutionButton.setVisible(false);
        newHighscorePanel.setVisible(false);
        //initialsTextField.setText("");
        timerLabel.setText(timerMinutes + ":" + timerSeconds);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showLeaderboardPanel = new javax.swing.JPanel();
        leaderboardLabel = new javax.swing.JLabel();
        easyLabel = new javax.swing.JLabel();
        mediumLabel = new javax.swing.JLabel();
        hardLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        easyTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mediumTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        hardTextArea = new javax.swing.JTextArea();
        selectDifficultyPanel = new javax.swing.JPanel();
        easyButton = new javax.swing.JButton();
        selectDifficultyLabel = new javax.swing.JLabel();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        programLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        guiMessageLabel = new javax.swing.JLabel();
        gameboardPanel = new javax.swing.JPanel();
        pos00 = new javax.swing.JTextField();
        checkSolutionButton = new javax.swing.JButton();
        showSolutionButton = new javax.swing.JButton();
        pos01 = new javax.swing.JTextField();
        pos02 = new javax.swing.JTextField();
        pos03 = new javax.swing.JTextField();
        pos04 = new javax.swing.JTextField();
        pos05 = new javax.swing.JTextField();
        pos06 = new javax.swing.JTextField();
        pos07 = new javax.swing.JTextField();
        pos08 = new javax.swing.JTextField();
        pos10 = new javax.swing.JTextField();
        pos11 = new javax.swing.JTextField();
        pos12 = new javax.swing.JTextField();
        pos13 = new javax.swing.JTextField();
        pos14 = new javax.swing.JTextField();
        pos15 = new javax.swing.JTextField();
        pos16 = new javax.swing.JTextField();
        pos17 = new javax.swing.JTextField();
        pos18 = new javax.swing.JTextField();
        pos20 = new javax.swing.JTextField();
        pos21 = new javax.swing.JTextField();
        pos22 = new javax.swing.JTextField();
        pos23 = new javax.swing.JTextField();
        pos24 = new javax.swing.JTextField();
        pos25 = new javax.swing.JTextField();
        pos26 = new javax.swing.JTextField();
        pos27 = new javax.swing.JTextField();
        pos28 = new javax.swing.JTextField();
        pos30 = new javax.swing.JTextField();
        pos31 = new javax.swing.JTextField();
        pos32 = new javax.swing.JTextField();
        pos33 = new javax.swing.JTextField();
        pos34 = new javax.swing.JTextField();
        pos35 = new javax.swing.JTextField();
        pos36 = new javax.swing.JTextField();
        pos37 = new javax.swing.JTextField();
        pos38 = new javax.swing.JTextField();
        pos40 = new javax.swing.JTextField();
        pos41 = new javax.swing.JTextField();
        pos42 = new javax.swing.JTextField();
        pos43 = new javax.swing.JTextField();
        pos44 = new javax.swing.JTextField();
        pos45 = new javax.swing.JTextField();
        pos46 = new javax.swing.JTextField();
        pos47 = new javax.swing.JTextField();
        pos48 = new javax.swing.JTextField();
        pos50 = new javax.swing.JTextField();
        pos51 = new javax.swing.JTextField();
        pos52 = new javax.swing.JTextField();
        pos53 = new javax.swing.JTextField();
        pos54 = new javax.swing.JTextField();
        pos55 = new javax.swing.JTextField();
        pos56 = new javax.swing.JTextField();
        pos57 = new javax.swing.JTextField();
        pos58 = new javax.swing.JTextField();
        pos60 = new javax.swing.JTextField();
        pos61 = new javax.swing.JTextField();
        pos62 = new javax.swing.JTextField();
        pos63 = new javax.swing.JTextField();
        pos64 = new javax.swing.JTextField();
        pos65 = new javax.swing.JTextField();
        pos66 = new javax.swing.JTextField();
        pos67 = new javax.swing.JTextField();
        pos68 = new javax.swing.JTextField();
        pos70 = new javax.swing.JTextField();
        pos71 = new javax.swing.JTextField();
        pos72 = new javax.swing.JTextField();
        pos73 = new javax.swing.JTextField();
        pos74 = new javax.swing.JTextField();
        pos75 = new javax.swing.JTextField();
        pos76 = new javax.swing.JTextField();
        pos77 = new javax.swing.JTextField();
        pos78 = new javax.swing.JTextField();
        pos80 = new javax.swing.JTextField();
        pos81 = new javax.swing.JTextField();
        pos82 = new javax.swing.JTextField();
        pos83 = new javax.swing.JTextField();
        pos84 = new javax.swing.JTextField();
        pos85 = new javax.swing.JTextField();
        pos86 = new javax.swing.JTextField();
        pos87 = new javax.swing.JTextField();
        pos88 = new javax.swing.JTextField();
        gameboardBannerLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        quitGameButton = new javax.swing.JButton();
        newHighscorePanel = new javax.swing.JPanel();
        highscoreLabel = new javax.swing.JLabel();
        highscoreDirectionsLabel = new javax.swing.JLabel();
        initialsTextField = new javax.swing.JTextField();
        enterInitialsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        showLeaderboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        leaderboardLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        leaderboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaderboardLabel.setText("Leaderboard");
        leaderboardLabel.setToolTipText("");
        leaderboardLabel.setMaximumSize(new java.awt.Dimension(100, 48));
        leaderboardLabel.setMinimumSize(new java.awt.Dimension(100, 48));
        leaderboardLabel.setName(""); // NOI18N
        leaderboardLabel.setPreferredSize(new java.awt.Dimension(100, 48));

        easyLabel.setBackground(new java.awt.Color(176, 141, 87));
        easyLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        easyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyLabel.setText("Easy");

        mediumLabel.setBackground(new java.awt.Color(192, 192, 192));
        mediumLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumLabel.setText("Medium");

        hardLabel.setBackground(new java.awt.Color(212, 175, 55));
        hardLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardLabel.setText("Hard");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        easyTextArea.setEditable(false);
        easyTextArea.setBackground(new java.awt.Color(176, 141, 87));
        easyTextArea.setColumns(2);
        easyTextArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        easyTextArea.setRows(3);
        easyTextArea.setTabSize(5);
        easyTextArea.setFocusable(false);
        jScrollPane1.setViewportView(easyTextArea);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        mediumTextArea.setEditable(false);
        mediumTextArea.setBackground(new java.awt.Color(192, 192, 192));
        mediumTextArea.setColumns(2);
        mediumTextArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        mediumTextArea.setRows(3);
        mediumTextArea.setTabSize(5);
        mediumTextArea.setFocusable(false);
        jScrollPane2.setViewportView(mediumTextArea);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        hardTextArea.setEditable(false);
        hardTextArea.setBackground(new java.awt.Color(212, 175, 55));
        hardTextArea.setColumns(2);
        hardTextArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        hardTextArea.setRows(3);
        hardTextArea.setTabSize(5);
        hardTextArea.setFocusable(false);
        jScrollPane3.setViewportView(hardTextArea);

        javax.swing.GroupLayout showLeaderboardPanelLayout = new javax.swing.GroupLayout(showLeaderboardPanel);
        showLeaderboardPanel.setLayout(showLeaderboardPanelLayout);
        showLeaderboardPanelLayout.setHorizontalGroup(
            showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showLeaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(showLeaderboardPanelLayout.createSequentialGroup()
                        .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(easyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mediumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addComponent(leaderboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196))
        );

        showLeaderboardPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        showLeaderboardPanelLayout.setVerticalGroup(
            showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLeaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leaderboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(easyLabel)
                    .addComponent(mediumLabel)
                    .addComponent(hardLabel))
                .addGap(9, 9, 9)
                .addGroup(showLeaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(151, 151, 151))
        );

        selectDifficultyPanel.setBackground(new java.awt.Color(255, 255, 255));

        easyButton.setBackground(new java.awt.Color(176, 141, 87));
        easyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        easyButton.setText("Easy");
        easyButton.setFocusable(false);
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });

        selectDifficultyLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        selectDifficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectDifficultyLabel.setText("Please Select Difficulty");
        selectDifficultyLabel.setToolTipText("");
        selectDifficultyLabel.setName(""); // NOI18N

        mediumButton.setBackground(new java.awt.Color(192, 192, 192));
        mediumButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumButton.setText("Medium");
        mediumButton.setFocusable(false);
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        hardButton.setBackground(new java.awt.Color(212, 175, 55));
        hardButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hardButton.setText("Hard");
        hardButton.setFocusable(false);
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });

        programLabel.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        programLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programLabel.setText("Play Sudoku!");
        programLabel.setToolTipText("");
        programLabel.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("* To play again, select difficulty of next game *");

        guiMessageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guiMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout selectDifficultyPanelLayout = new javax.swing.GroupLayout(selectDifficultyPanel);
        selectDifficultyPanel.setLayout(selectDifficultyPanelLayout);
        selectDifficultyPanelLayout.setHorizontalGroup(
            selectDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectDifficultyPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(selectDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(programLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectDifficultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(selectDifficultyPanelLayout.createSequentialGroup()
                        .addComponent(easyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(mediumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectDifficultyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(selectDifficultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        selectDifficultyPanelLayout.setVerticalGroup(
            selectDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectDifficultyPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(programLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectDifficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(selectDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(easyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        gameboardPanel.setBackground(new java.awt.Color(0, 0, 0));

        pos00.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos00ActionPerformed(evt);
            }
        });

        checkSolutionButton.setBackground(new java.awt.Color(51, 204, 0));
        checkSolutionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkSolutionButton.setText("Check Solution");
        checkSolutionButton.setFocusable(false);
        checkSolutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSolutionButtonActionPerformed(evt);
            }
        });

        showSolutionButton.setBackground(new java.awt.Color(255, 255, 51));
        showSolutionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showSolutionButton.setText("Show Solution");
        showSolutionButton.setFocusable(false);
        showSolutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSolutionButtonActionPerformed(evt);
            }
        });

        pos01.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos01.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos02.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos03.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos03.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos04.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos04.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos05.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos05.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos06.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos06.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos07.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos07.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos08.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos08.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos27.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos28.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos30.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos31.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos32.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos33.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos34.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos35.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos35.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos36.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos37.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos37.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos38.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos38.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos40.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos40.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos41.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos41.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos42.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos42.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos43.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos43.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos44.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos45.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos45.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos46.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos46.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos47.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos47.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos48.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos48.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos50.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos50.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos51.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos51.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos52.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos52.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos53.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos53.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos54.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos54.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos55.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos56.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos56.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos57.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos57.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos58.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos58.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos60.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos60.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos61.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos61.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos62.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos62.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos63.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos63.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos64.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos64.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos65.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos65.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos66.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos67.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos67.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos68.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos68.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos70.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos70.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos71.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos71.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos72.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos72.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos73.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos73.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos74.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos74.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos75.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos75.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos76.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos76.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos77.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos77.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos78.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos78.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos80.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos80.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos81.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos81.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos82.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos82.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos83.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos83.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos84.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos84.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos85.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos85.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos86.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos86.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos87.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos87.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pos88.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pos88.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gameboardBannerLabel.setBackground(new java.awt.Color(255, 255, 255));
        gameboardBannerLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        gameboardBannerLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameboardBannerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameboardBannerLabel.setText("Play Sudoku!");

        timerLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 28)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(255, 255, 255));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        quitGameButton.setBackground(new java.awt.Color(255, 51, 51));
        quitGameButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quitGameButton.setText("Quit Game");
        quitGameButton.setFocusable(false);
        quitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameboardPanelLayout = new javax.swing.GroupLayout(gameboardPanel);
        gameboardPanel.setLayout(gameboardPanelLayout);
        gameboardPanelLayout.setHorizontalGroup(
            gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameboardPanelLayout.createSequentialGroup()
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameboardPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameboardBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos70, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos71, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos72, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos73, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos74, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos75, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos76, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos77, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos78, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos60, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos61, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos62, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos63, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos64, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos65, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos66, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos67, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos68, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos56, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos57, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos58, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos46, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos47, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos48, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos36, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos37, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos03, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos04, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos05, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos06, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos07, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos08, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                .addComponent(pos80, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(gameboardPanelLayout.createSequentialGroup()
                                        .addComponent(pos81, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos82, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(gameboardPanelLayout.createSequentialGroup()
                                                .addComponent(pos83, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pos84, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pos85, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pos86, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos87, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gameboardPanelLayout.createSequentialGroup()
                                        .addComponent(checkSolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(showSolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos88, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(gameboardPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(quitGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        gameboardPanelLayout.setVerticalGroup(
            gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameboardPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(gameboardBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos03, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos04, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos05, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos06, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos07, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos08, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos36, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos37, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos38, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos46, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos47, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos48, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos56, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos57, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos58, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos60, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos61, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos62, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos63, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos64, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos65, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos66, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos67, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos68, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos70, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos71, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos72, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos73, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos74, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos75, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos76, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos77, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos78, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos80, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos81, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos82, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos83, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos84, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos85, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos86, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos87, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos88, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(gameboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(quitGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        gameboardPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkSolutionButton, showSolutionButton});

        newHighscorePanel.setBackground(new java.awt.Color(255, 255, 255));

        highscoreLabel.setBackground(new java.awt.Color(255, 255, 255));
        highscoreLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        highscoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoreLabel.setText("New HighScore!");
        highscoreLabel.setToolTipText("");
        highscoreLabel.setMaximumSize(new java.awt.Dimension(100, 48));
        highscoreLabel.setMinimumSize(new java.awt.Dimension(100, 48));
        highscoreLabel.setName(""); // NOI18N
        highscoreLabel.setPreferredSize(new java.awt.Dimension(100, 48));

        highscoreDirectionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        highscoreDirectionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoreDirectionsLabel.setText("Please type your initials in the box below and click enter");

        initialsTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        initialsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        enterInitialsButton.setBackground(new java.awt.Color(255, 153, 0));
        enterInitialsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enterInitialsButton.setText("Enter");
        enterInitialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterInitialsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newHighscorePanelLayout = new javax.swing.GroupLayout(newHighscorePanel);
        newHighscorePanel.setLayout(newHighscorePanelLayout);
        newHighscorePanelLayout.setHorizontalGroup(
            newHighscorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHighscorePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newHighscorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newHighscorePanelLayout.createSequentialGroup()
                        .addComponent(highscoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newHighscorePanelLayout.createSequentialGroup()
                        .addComponent(highscoreDirectionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
            .addGroup(newHighscorePanelLayout.createSequentialGroup()
                .addGroup(newHighscorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newHighscorePanelLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(initialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newHighscorePanelLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(enterInitialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newHighscorePanelLayout.setVerticalGroup(
            newHighscorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHighscorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(highscoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highscoreDirectionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(initialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInitialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectDifficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showLeaderboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newHighscorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(selectDifficultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showLeaderboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newHighscorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(gameboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method used to start game timer
    public void startTimer() {
        gameTimer.start();
    }

    // Method used to stop game timer
    public void stopTimer() {
        gameTimer.stop();
    }

    // Method used to reset game timer
    public void resetTimer() {
        gameTimer.stop();
        elapsedTime = 0;
        seconds = 0;
        minutes = 0;
        timerSeconds = String.format("%02d", seconds);
        timerMinutes = String.format("%02d", minutes);
        timerLabel.setText(timerMinutes + ":" + timerSeconds);
    }

    // Method used to connect textfields with the gameboard 2D array structure
    private void loadList() {
        positions.add(pos00);
        positions.add(pos01);
        positions.add(pos02);
        positions.add(pos03);
        positions.add(pos04);
        positions.add(pos05);
        positions.add(pos06);
        positions.add(pos07);
        positions.add(pos08);
        positions.add(pos10);
        positions.add(pos11);
        positions.add(pos12);
        positions.add(pos13);
        positions.add(pos14);
        positions.add(pos15);
        positions.add(pos16);
        positions.add(pos17);
        positions.add(pos18);
        positions.add(pos20);
        positions.add(pos21);
        positions.add(pos22);
        positions.add(pos23);
        positions.add(pos24);
        positions.add(pos25);
        positions.add(pos26);
        positions.add(pos27);
        positions.add(pos28);
        positions.add(pos30);
        positions.add(pos31);
        positions.add(pos32);
        positions.add(pos33);
        positions.add(pos34);
        positions.add(pos35);
        positions.add(pos36);
        positions.add(pos37);
        positions.add(pos38);
        positions.add(pos40);
        positions.add(pos41);
        positions.add(pos42);
        positions.add(pos43);
        positions.add(pos44);
        positions.add(pos45);
        positions.add(pos46);
        positions.add(pos47);
        positions.add(pos48);
        positions.add(pos50);
        positions.add(pos51);
        positions.add(pos52);
        positions.add(pos53);
        positions.add(pos54);
        positions.add(pos55);
        positions.add(pos56);
        positions.add(pos57);
        positions.add(pos58);
        positions.add(pos60);
        positions.add(pos61);
        positions.add(pos62);
        positions.add(pos63);
        positions.add(pos64);
        positions.add(pos65);
        positions.add(pos66);
        positions.add(pos67);
        positions.add(pos68);
        positions.add(pos70);
        positions.add(pos71);
        positions.add(pos72);
        positions.add(pos73);
        positions.add(pos74);
        positions.add(pos75);
        positions.add(pos76);
        positions.add(pos77);
        positions.add(pos78);
        positions.add(pos80);
        positions.add(pos81);
        positions.add(pos82);
        positions.add(pos83);
        positions.add(pos84);
        positions.add(pos85);
        positions.add(pos86);
        positions.add(pos87);
        positions.add(pos88);
    }

    // Method used to generate the GUI gameboard visual state
    private void generateGameState(int difficulty) {
        // Setting timer
        resetTimer();
        startTimer();
        populateLeaderboard();

        // Setting button visibility and highscore textbox to blank string
        checkSolutionButton.setVisible(true);
        showSolutionButton.setVisible(true);
        gameboardBannerLabel.setText("Play Sudoku!");
        gameboardBannerLabel.setForeground(Color.white);
        guiMessageLabel.setText("");

        // Setting all JTextField background colors to white
        for (int i = 0; i < positions.size(); i++) {
            positions.get(i).setBackground(Color.white);
        }

        // Checking if selected difficulty has remaining boards or not
        if (SelectDifficulty.checkDifficulty(difficulty)) {
            resetTimer();
            if (SelectDifficulty.allBoardsUsed == true) {
                for (int i = 0; i < positions.size(); i++) {
                    positions.get(i).setText("");;
                }
                easyButton.setEnabled(false);
                mediumButton.setEnabled(false);
                hardButton.setEnabled(false);
                guiMessageLabel.setText(SelectDifficulty.getGuiMessage());
            } else {
                switch (difficulty) {
                    case 1:
                        easyButton.setEnabled(false);
                        guiMessageLabel.setVisible(true);
                        guiMessageLabel.setText(SelectDifficulty.getGuiMessage());
                        break;
                    case 2:
                        mediumButton.setEnabled(false);
                        guiMessageLabel.setVisible(true);
                        guiMessageLabel.setText(SelectDifficulty.getGuiMessage());
                        break;
                    case 3:
                        hardButton.setEnabled(false);
                        guiMessageLabel.setVisible(true);
                        guiMessageLabel.setText(SelectDifficulty.getGuiMessage());
                        break;
                    default:
                        break;
                }
            }
        } else {
            gameboard.loadBoard(SelectDifficulty.getBoard());
            gameboard.generateSolved();

            gameboard.print(gameboard.getBoard());
            System.out.println("\n");
            gameboard.print(gameboard.getSolvedBoard());

            // Declaring variables
            int[][] game = gameboard.getBoard();
            int counter = 0;

            // Loop used to take gameboard array info and populate gameboard
            for (int j = 0; j < 9; j++) {
                for (int i = 0; i < 9; i++) {
                    if (game[j][i] == 0) {
                        positions.get(counter).setText("");
                        positions.get(counter).setEditable(true);
                    } else {
                        positions.get(counter).setText("" + game[j][i]);
                        positions.get(counter).setEditable(false);
                    }

                    counter++;
                }
            }
        }
    }

    // Method used to populate GUI leaderboard
    private void populateLeaderboard() {
        try {
            easyTextArea.setText(LeaderBoardScore.readScores(1));
            mediumTextArea.setText(LeaderBoardScore.readScores(2));
            hardTextArea.setText(LeaderBoardScore.readScores(3));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // Setting difficulty of game to easy and calling method to start game
        try {
            int difficulty = 1;
            generateGameState(difficulty);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_easyButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        // Setting difficulty of game to medium and calling method to start game
        try {
            int difficulty = 2;
            generateGameState(difficulty);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        // Setting difficulty of game to hard and calling method to start game
        try {
            int difficulty = 3;
            generateGameState(difficulty);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_hardButtonActionPerformed

    private void pos00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos00ActionPerformed
        // Accidentally made this, can't get rid of it...
    }//GEN-LAST:event_pos00ActionPerformed

    private void checkSolutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSolutionButtonActionPerformed
        // Declaring variables
        boolean hasBeenSolved = true;
        int[][] game = gameboard.getBoard();
        int[][] solvedGame = gameboard.getSolvedBoard();
        int counter = 0;

        // Stopping game timer
        stopTimer();

        // Loop used to check mark incorrect integer entries
        for (int j = 0; j < 9; j++) {
            for (int i = 0; i < 9; i++) {
                // If statement used to check if anything has been entered into
                // the gameboard by the user
                if (positions.get(counter).getText().equals("")) {
                    hasBeenSolved = false;
                }

                // If statement used to highlight any incorrect user entries
                // on the gameboard to red
                if (game[j][i] == 0) {
                    if (!positions.get(counter).getText().equals("" + solvedGame[j][i]) && !positions.get(counter).getText().equals("")) {
                        positions.get(counter).setBackground(Color.red);
                        hasBeenSolved = false;
                    }
                }
                counter++;
            }
        }

        // Checking if gameboard has been solved, display message banner with
        // game results
        if (hasBeenSolved) {
            gameboardBannerLabel.setText("Successful Sudoku!");
            gameboardBannerLabel.setForeground(Color.green);
            checkSolutionButton.setVisible(false);
            playerTime = (elapsedTime / 1000);

            // Checks if solved board qualifies for a new highscore
            if (LeaderBoardScore.checkScore(SelectDifficulty.boardDifficulty, playerTime)) {
                newHighscorePanel.setVisible(true);
            }
        } else {
            gameboardBannerLabel.setText("Failed to Sudoku!");
            gameboardBannerLabel.setForeground(Color.red);
            checkSolutionButton.setVisible(false);
        }

        // Removing used gameboard
        SelectDifficulty.removeBoard();
    }//GEN-LAST:event_checkSolutionButtonActionPerformed

    private void showSolutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSolutionButtonActionPerformed
        // Declaring variables
        int[][] game = gameboard.getBoard();
        int[][] solvedGame = gameboard.getSolvedBoard();
        int counter = 0;

        // Stopping game timer
        stopTimer();

        // Setting anti-cheat provision by taking check solution button away
        // after clicking show solution button to see the solved sudoku board
        checkSolutionButton.setVisible(false);

        // Setting all JTextField background colors to white
        for (int j = 0; j < 9; j++) {
            for (int i = 0; i < 9; i++) {
                // If statement used to highlight any incorrect user entries
                // on the gameboard to red
                if (game[j][i] == 0) {
                    if (!positions.get(counter).getText().equals("" + solvedGame[j][i]) && !positions.get(counter).getText().equals("")) {
                        positions.get(counter).setBackground(Color.yellow);
                    }

                }
                counter++;
            }
        }

        // Resetting counter to populate board with answers
        counter = 0;

        // Loop used to populate correct answers to gameboard on GUI
        for (int j = 0; j < 9; j++) {
            for (int i = 0; i < 9; i++) {

                positions.get(counter).setText("" + solvedGame[j][i]);
                counter++;
            }
        }

        // Removing used gameboard
        SelectDifficulty.removeBoard();
    }//GEN-LAST:event_showSolutionButtonActionPerformed

    private void quitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitGameButtonActionPerformed
        // Closing program
        System.exit(0);
    }//GEN-LAST:event_quitGameButtonActionPerformed

    private void enterInitialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterInitialsButtonActionPerformed
        // Gets user initials from new highscore panel and sends them to
        // LeaderBoardScore
        try {
            String playerInitials = initialsTextField.getText();
            LeaderBoardScore.writeScore(SelectDifficulty.boardDifficulty, playerInitials, playerTime);
            populateLeaderboard();
            newHighscorePanel.setVisible(false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_enterInitialsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMenu().setVisible(true);
                } catch (IOException e) {
                    System.out.println(e.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkSolutionButton;
    private javax.swing.JButton easyButton;
    private javax.swing.JLabel easyLabel;
    private javax.swing.JTextArea easyTextArea;
    private javax.swing.JButton enterInitialsButton;
    private javax.swing.JLabel gameboardBannerLabel;
    private javax.swing.JPanel gameboardPanel;
    private javax.swing.JLabel guiMessageLabel;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel hardLabel;
    private javax.swing.JTextArea hardTextArea;
    private javax.swing.JLabel highscoreDirectionsLabel;
    private javax.swing.JLabel highscoreLabel;
    private javax.swing.JTextField initialsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel leaderboardLabel;
    private javax.swing.JButton mediumButton;
    private javax.swing.JLabel mediumLabel;
    private javax.swing.JTextArea mediumTextArea;
    private javax.swing.JPanel newHighscorePanel;
    private javax.swing.JTextField pos00;
    private javax.swing.JTextField pos01;
    private javax.swing.JTextField pos02;
    private javax.swing.JTextField pos03;
    private javax.swing.JTextField pos04;
    private javax.swing.JTextField pos05;
    private javax.swing.JTextField pos06;
    private javax.swing.JTextField pos07;
    private javax.swing.JTextField pos08;
    private javax.swing.JTextField pos10;
    private javax.swing.JTextField pos11;
    private javax.swing.JTextField pos12;
    private javax.swing.JTextField pos13;
    private javax.swing.JTextField pos14;
    private javax.swing.JTextField pos15;
    private javax.swing.JTextField pos16;
    private javax.swing.JTextField pos17;
    private javax.swing.JTextField pos18;
    private javax.swing.JTextField pos20;
    private javax.swing.JTextField pos21;
    private javax.swing.JTextField pos22;
    private javax.swing.JTextField pos23;
    private javax.swing.JTextField pos24;
    private javax.swing.JTextField pos25;
    private javax.swing.JTextField pos26;
    private javax.swing.JTextField pos27;
    private javax.swing.JTextField pos28;
    private javax.swing.JTextField pos30;
    private javax.swing.JTextField pos31;
    private javax.swing.JTextField pos32;
    private javax.swing.JTextField pos33;
    private javax.swing.JTextField pos34;
    private javax.swing.JTextField pos35;
    private javax.swing.JTextField pos36;
    private javax.swing.JTextField pos37;
    private javax.swing.JTextField pos38;
    private javax.swing.JTextField pos40;
    private javax.swing.JTextField pos41;
    private javax.swing.JTextField pos42;
    private javax.swing.JTextField pos43;
    private javax.swing.JTextField pos44;
    private javax.swing.JTextField pos45;
    private javax.swing.JTextField pos46;
    private javax.swing.JTextField pos47;
    private javax.swing.JTextField pos48;
    private javax.swing.JTextField pos50;
    private javax.swing.JTextField pos51;
    private javax.swing.JTextField pos52;
    private javax.swing.JTextField pos53;
    private javax.swing.JTextField pos54;
    private javax.swing.JTextField pos55;
    private javax.swing.JTextField pos56;
    private javax.swing.JTextField pos57;
    private javax.swing.JTextField pos58;
    private javax.swing.JTextField pos60;
    private javax.swing.JTextField pos61;
    private javax.swing.JTextField pos62;
    private javax.swing.JTextField pos63;
    private javax.swing.JTextField pos64;
    private javax.swing.JTextField pos65;
    private javax.swing.JTextField pos66;
    private javax.swing.JTextField pos67;
    private javax.swing.JTextField pos68;
    private javax.swing.JTextField pos70;
    private javax.swing.JTextField pos71;
    private javax.swing.JTextField pos72;
    private javax.swing.JTextField pos73;
    private javax.swing.JTextField pos74;
    private javax.swing.JTextField pos75;
    private javax.swing.JTextField pos76;
    private javax.swing.JTextField pos77;
    private javax.swing.JTextField pos78;
    private javax.swing.JTextField pos80;
    private javax.swing.JTextField pos81;
    private javax.swing.JTextField pos82;
    private javax.swing.JTextField pos83;
    private javax.swing.JTextField pos84;
    private javax.swing.JTextField pos85;
    private javax.swing.JTextField pos86;
    private javax.swing.JTextField pos87;
    private javax.swing.JTextField pos88;
    private javax.swing.JLabel programLabel;
    private javax.swing.JButton quitGameButton;
    private javax.swing.JLabel selectDifficultyLabel;
    private javax.swing.JPanel selectDifficultyPanel;
    private javax.swing.JPanel showLeaderboardPanel;
    private javax.swing.JButton showSolutionButton;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
